#!/bin/bash

template="badget"
while IFS="" read -r line || [ -n "$line" ] ; do
	name="$(echo "$line" | cut -f1)"
	left="$(echo "$line" | cut -f2)"
	right="$(echo "$line" | cut -f3)"
	center="$(echo "$line" | cut -f4)"
	./badge "$template" "$name" "$left" "$right" "$center" &
done <coords
